### PR TITLE
134 download button does not work

### LINKED ISSUE #134: Download button does not work
**Overview**
The current download button on the application is outdated and non-functional. When clicked, it should download all details related to the filtered results in an Excel sheet format, but this is not working as expected. This issue focuses on fixing the download button to ensure that filtered data can be successfully exported as an Excel file.

**Expected Behavior**
When the user clicks the download button, the system should generate and download an Excel file containing all the relevant details of the filtered results without errors.

**Acceptance Criteria** 
- [ ]  The download button successfully exports an Excel file with details related to the filtered results.
- [ ]  The Excel file includes all relevant data based on the applied filters.
- [ ]  Excel file is properly formatted.
- [ ]  The download functionality is tested with various filter combinations, and no errors occur during the process.
- [ ]  The download works for both small and large datasets.

### PR DESCRIPTION
**Pull request by dracpak**
Fixes #134 

**What was changed?**

The download button functionality was tweaked so that when the user pressed download an error message wouldn't pop up.

**Why was it changed?**

Currently, when the user pressed download for a particular dataset, they encountered errors. This really impacted the experience of the user and made the application seem broken. To fix this, we needed the download button to actually prompt the downloading of a csv file rather than show an error message.

**How was it changed?**

For this change, we found that the `get_selected_systems()` function was bugged in the `postgres_connector.py` file. The query referred to a non-existent `label` column in the database that was causing errors in the query, and in turn, not returning the DB entries that needed to be imported. The change fixes this by reassembling the label values in the table in the UI (the target for indexing) by concatenating rows that do exist. We also need to make changes in `ExploreSystems.js` in the `downloadCSV()` function to make sure the csv file returns correctly formatted.

**Screenshots that show the changes (if applicable):**

### CODE REVIEW

**Comment by BradleySheldon** [comment]
The result.csv file mostly compiles the way it should, but some columns/ labels are split up incorrectly. Definitely going in the right direction and solid overall though.

**Comment by suprajamannava17** [comment]
The download button is working well, and it’s great to see that the CSV file is generating correctly. However, while the button downloads a CSV file, some of the data in it doesn't seem correct, with the data split up incorrectly and too many additional columns present. Additionally, the filters aren't applying as expected, as the total count remains at 147 maps even when filters are used. This important because the download feature should reflect the filtered results, aligning with user needs and ensuring accurate data retrieval. I recommend reviewing the filter logic to ensure it works seamlessly with the download functionality. Once the filters are applied properly, the CSV should only include the filtered data. Keep up the good work, and focus on integrating these elements to meet the feature requirements fully!

**Comment by iamsyedomair** [comment]
The label construction logic is now embedded in the SQL query. This approach might lead to inconsistencies if the label format changes in the future or if it's constructed differently in other parts of the application. One thing if I had to suggest maybe for future work consider extracting this label construction logic into a separate function or method that can be reused across the application, ensuring consistency and easier maintenance.

**Comment by dracpak** [comment]
> The download button is working well, and it’s great to see that the CSV file is generating correctly. However, while the button downloads a CSV file, some of the data in it doesn't seem correct, with the data split up incorrectly and too many additional columns present. Additionally, the filters aren't applying as expected, as the total count remains at 147 maps even when filters are used. This important because the download feature should reflect the filtered results, aligning with user needs and ensuring accurate data retrieval. I recommend reviewing the filter logic to ensure it works seamlessly with the download functionality. Once the filters are applied properly, the CSV should only include the filtered data. Keep up the good work, and focus on integrating these elements to meet the feature requirements fully!

I cannot replicate the issue with the filters not applying to the CSV output, can you test with the code I pushed and let me know what filters break it?

**Review by suprajamannava17 — APPROVED** [review]
looks good to me

**Pull request merged**
