### PR TITLE
Issue#141/fixing field filter

### LINKED ISSUE #141: filter by field label does not work
**Overview**
The current filtering system for field labels, which falls under the "field of definition" in the filters section, is not functioning as expected. When entering certain field labels (e.g., 2.2.5.1), the system returns 0 results, although there should be matching records. This issue affects the usability of the filtering feature, leading to incorrect or empty search results.

**Tasks**
Debug the Filtering Functionality
Check Database Structure
Update Filter Logic

**Expected Behavior**
When entering a valid field label in the filter (such as 2.2.5.1), the system should return all relevant records that match this label.

### PR DESCRIPTION
**Pull request by dracpak**
…s to make sure the query formats properly

Fixes #141

**What was changed?**

The `build_where_text()` class was changed. Specifically in the case where the `base_field_label` is used, the input string to `conditons.append()` was changed. 

**Why was it changed?**

When the user would enter anything into the `Label` subfield of the `Field of Definition` filter, the application would respond with "no data meets that criteria", even if there was data that should have matched. This made the filter entirely inoperable and the UI less friendly, as there was no indication of what was going wrong on the user side.

**How was it changed?**

In the old code, the entire input was surrounded by two single quotes making the entire text a string, which included a string variable. In addition, the string around the wildcard characters needs single quotes in order to execute the SQL query correctly. By adding this and tweaking the string so the string variable is a variable rather than a string of the variable name, the query now calls correctly.

### CODE REVIEW

**Review by iamsyedomair — COMMENTED** [review]
I think it is a simple and good fix and should be approved.

**Review by iamsyedomair — COMMENTED** [review]
even though you have restored it back to its original state i wonder if you might need to create a new pull request all together because anyone could still just see the username and password by going through the commit history. but then again i leave judgement to the team lead and professor Holdener.

**Comment by suprajamannava17** [comment]
> …s to make sure the query formats properly
> 
> Fixes #141
> 
> **What was changed?**
> 
> The `build_where_text()` class was changed. Specifically in the case where the `base_field_label` is used, the input string to `conditons.append()` was changed.
> 
> **Why was it changed?**
> 
> When the user would enter anything into the `Label` subfield of the `Field of Definition` filter, the application would respond with "no data meets that criteria", even if there was data that should have matched. This made the filter entirely inoperable and the UI less friendly, as there was no indication of what was going wrong on the user side.
> 
> **How was it changed?**
> 
> In the old code, the entire input was surrounded by two single quotes making the entire text a string, which included a string variable. In addition, the string around the wildcard characters needs single quotes in order to execute the SQL query correctly. By adding this and tweaking the string so the string variable is a variable rather than a string of the variable name, the query now calls correctly.

Great job on debugging the field filtering issue! Your code fix effectively addresses the core problem, ensuring the field label filters correctly, and the feature now works as expected. This solution aligns well with the product’s priorities, as it directly improves user functionality while maintaining the overall design and architecture. The PR is currently failing due to Pylint warnings, but these are minor linting issues that can be easily resolved to pass the workflow.
Regarding your first commit, you have the option to either fix the issue in the current PR by removing the sensitive data from the branch’s history or create a new PR after cleaning the credentials from the history. I would appreciate Professor Holdener’s guidance on which method she recommends as the best practice. Overall, this is a great fix, and with some minor adjustments, it will be ready for final approval. Keep up the good work!

**Comment by suprajamannava17** [comment]
Great job on debugging the field filtering issue! Your code fix effectively addresses the core problem, ensuring the field label filters correctly, and the feature now works as expected. This solution aligns well with the product’s priorities, as it directly improves user functionality while maintaining the overall design and architecture. The PR is currently failing due to Pylint warnings, but these are minor linting issues that can be easily resolved to pass the workflow.
Regarding your first commit, you have the option to either fix the issue in the current PR by removing the sensitive data from the branch’s history or create a new PR after cleaning the credentials from the history. I would appreciate Professor Holdener’s guidance on which method she recommends as the best practice. Overall, this is a great fix, and with some minor adjustments, it will be ready for final approval. Keep up the good work!

**Comment by kate-holdener** [comment]
> even though you have restored it back to its original state i wonder if you might need to create a new pull request all together because anyone could still just see the username and password by going through the commit history. but then again i leave judgement to the team lead and professor Holdener.

The password needs to be changed, because there is a way find it now.

**Review by suprajamannava17 — APPROVED** [review]

**Review by BradleySheldon — APPROVED** [review]

**Pull request merged**
