### PR TITLE
Fix cardinality sub filter for rational periodic point filter #142

### LINKED ISSUE #142: rational periodic point filter does not work
**Overview**
The filters for Cardinality and Largest Cycle under rational periodic points are not functioning as expected. When a user enters a value in the filter, the maps that are returned do not match the specified filter values. This affects the functionality of the filter, making it difficult to retrieve accurate results for rational periodic points.

**Tasks**
Review the Filter Logic of the rational periodic point filter in both the frontend and backend.
Check Database Queries
Refactor the Filter Logic if Necessary

**Expected Behavior**
When a value is entered into the rational periodic point filter, the system should return maps that match the filter criteria.

In the below image total number of maps displayed is 147, and even after applying filter values, the total remains the same regardless of the values entered. This indicates that the filtering is not functioning correctly, as the number of maps should adjust based on the filter criteria.
image

### PR DESCRIPTION
**Pull request by BradleySheldon**
Fixes #142

**What was changed?**
The cardinality sub-filter under rational periodic points has been implemented.

*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*
Frontend: modified the filter handling for cp_cardinality so that the correct filter is passed from the UI.
Backend: Updated the database query logic to handle cp_cardinality correctly

**Why was it changed?**
This issue was changed so the users can more effectively filter the data they are searching for.

*Here, describe the issue that you are fixing with this code, and why your code fixes it.*
The cardinality filter under Rational Periodic Points was not functioning at all. It was returning all results regardless of the filter input. The fix is so that users can now filter this data based on the criteria.

**How was it changed?**
This code was changed by adjusting the filter logic of the Rational Periodic Point filter in both the frontend and backend as well as reviewing which database queries to implement.

*Here, get into detail about what files you modified, and talk about the most important lines in regards to fixing the issue.*
Added support to postgres_connector.py to filter by cp_cardinality in SQL queries. In FilterContext.js I added the cp_cardinality key to the filter context to pass the correct filter value to the backend. And in ExploreSystems.js the logic was modified to capture and send the cp_cardinality filter from the UI to the backend. 

Remaining Issue:
Largest cycle is still not implemented, I could not find where this data was being stored to be implemented

**Screenshots that show the changes (if applicable):**

### CODE REVIEW

**Review by dracpak — CHANGES_REQUESTED** [review]
The cardinality filter appears to work based off of the cp_cardinality. Largest cycle still needs to be implemented. Also, Cardinality and Largest Cycle should only ever be numbers, so consider changing the text box to only accept numbers to prevent user error and mitigate SQL Injection (although there are other places to inject)

**Comment by suprajamannava17** [comment]
The cardinality filter is functioning as expected for numerical values, but allowing text input could lead to errors and security concerns. I recommend updating the input field to accept numbers only, as both fields should be numerical. While the filter logic for cardinality is in place, the largest cycle feature still needs to be implemented to fully meet the feature requirements. Great progress so far, but let’s focus on refining input validation and completing the largest cycle logic.

**Review by dracpak — COMMENTED** [review]
Cardinality filter works however the statistics page breaks because it's trying to reference columns in the where text that don't exist. PR 157 has a fix for this if you just want to implement it quickly, although it also could be improved with a variable.

**Review by suprajamannava17 — APPROVED** [review]

**Comment by suprajamannava17** [comment]
All the filters are working fine

**Pull request merged**
